import { rawDb } from "../../../../../db/fsl";

export const dynamic = "force-dynamic";

export async function GET(
  _: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const db = rawDb();
    const tournament = await db
      .prepare("SELECT id,name,edition,accent FROM tournaments WHERE id=? AND status IN ('active','completed') AND (is_public=1 OR is_public IS NULL)")
      .bind(id)
      .first();
    if (!tournament)
      return Response.json({ error: "Torneo non disponibile" }, { status: 404 });
    const [posts, awards, categories, matches, standings, scorers, events, outcomes, fantasyRatings, badges] = await Promise.all([
      db.prepare("SELECT p.id,p.type,p.title,p.excerpt,p.body,p.media_key AS mediaKey,p.video_url AS videoUrl,p.published_at AS publishedAt,t.name AS teamName FROM editorial_posts p LEFT JOIN teams t ON t.id=p.team_id WHERE p.tournament_id=? AND p.status='published' AND datetime(p.published_at)<=datetime('now') ORDER BY p.published_at DESC LIMIT 12").bind(id).all(),
      db.prepare("SELECT a.id,a.scope,a.type,a.title,CASE WHEN a.player_id IS NULL OR (p.profile_visibility='public' AND p.media_consent=1) THEN a.recipient_name ELSE 'Giocatore' END AS recipientName,a.note,a.media_key AS mediaKey,a.awarded_at AS awardedAt,t.name AS teamName FROM awards a LEFT JOIN teams t ON t.id=a.team_id LEFT JOIN players p ON p.id=a.player_id WHERE a.tournament_id=? AND a.status='published' ORDER BY a.awarded_at DESC LIMIT 12").bind(id).all(),
      db.prepare("SELECT id,category,division,name,kind FROM competition_settings WHERE tournament_id=? AND enabled=1 ORDER BY category,division,name").bind(id).all(),
      db.prepare("SELECT m.id,m.home_team_id AS homeTeamId,m.away_team_id AS awayTeamId,m.category,m.division,m.match_day AS matchDay,m.starts_at AS startsAt,m.venue,m.field,m.referee_name AS refereeName,m.status,m.competition_id AS competitionId,m.stage,m.round_name AS roundName,m.bracket_round AS bracketRound,m.bracket_tie_id AS bracketTieId,m.bracket_leg AS bracketLeg,c.name AS competitionName,h.name AS home,h.short_name AS homeShort,h.primary_color AS homeColor,h.crest_key AS homeCrestKey,a.name AS away,a.short_name AS awayShort,a.primary_color AS awayColor,a.crest_key AS awayCrestKey,r.home_score AS homeScore,r.away_score AS awayScore,r.home_penalty_score AS homePenaltyScore,r.away_penalty_score AS awayPenaltyScore FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id LEFT JOIN competition_settings c ON c.id=m.competition_id LEFT JOIN match_reports r ON r.match_id=m.id WHERE m.tournament_id=? AND m.status!='cancelled' ORDER BY CASE WHEN datetime(m.starts_at)>=datetime('now') THEN 0 ELSE 1 END,CASE WHEN datetime(m.starts_at)>=datetime('now') THEN datetime(m.starts_at) END ASC,datetime(m.starts_at) DESC LIMIT 80").bind(id).all(),
      db.prepare("SELECT cs.id AS competitionId,cs.name AS competitionName,cs.category,cs.division,t.id,t.name,t.short_name AS shortName,t.primary_color AS primaryColor,t.crest_key AS crestKey,COUNT(m.id) AS played,COALESCE(SUM(CASE WHEN m.home_team_id=t.id THEN r.home_score ELSE r.away_score END),0) AS gf,COALESCE(SUM(CASE WHEN m.home_team_id=t.id THEN r.away_score ELSE r.home_score END),0) AS ga,COALESCE(SUM(CASE WHEN (m.home_team_id=t.id AND r.home_score>r.away_score) OR (m.away_team_id=t.id AND r.away_score>r.home_score) THEN 3 WHEN r.home_score=r.away_score THEN 1 ELSE 0 END),0) AS points FROM competition_settings cs JOIN tournament_teams tt ON tt.tournament_id=cs.tournament_id JOIN teams t ON t.id=tt.team_id LEFT JOIN matches m ON m.competition_id=cs.id AND m.stage='qualification' AND (m.home_team_id=t.id OR m.away_team_id=t.id) AND m.status IN ('official','rectified') LEFT JOIN match_reports r ON r.match_id=m.id WHERE cs.tournament_id=? AND cs.enabled=1 AND cs.kind!='knockout' AND tt.status!='withdrawn' AND ((EXISTS (SELECT 1 FROM competition_team_entries x WHERE x.competition_id=cs.id) AND EXISTS (SELECT 1 FROM competition_team_entries x WHERE x.competition_id=cs.id AND x.team_id=t.id AND x.status!='withdrawn')) OR (NOT EXISTS (SELECT 1 FROM competition_team_entries x WHERE x.competition_id=cs.id) AND tt.category=cs.category AND tt.division=cs.division)) GROUP BY cs.id,cs.name,cs.category,cs.division,t.id,t.name,t.short_name ORDER BY cs.category,cs.division,cs.name,points DESC,(gf-ga) DESC,gf DESC").bind(id).all(),
      db.prepare("SELECT s.player_id AS playerId,COALESCE(p.public_name,p.first_name||' '||substr(p.last_name,1,1)||'.') AS playerName,p.photo_key AS photoKey,t.name AS teamName,t.short_name AS teamShort,s.goals,s.assists,s.appearances FROM player_tournament_stats s JOIN players p ON p.id=s.player_id JOIN teams t ON t.id=p.team_id JOIN tournament_teams tt ON tt.team_id=p.team_id AND tt.tournament_id=s.tournament_id WHERE s.tournament_id=? AND p.profile_visibility='public' AND p.media_consent=1 AND s.goals>0 ORDER BY s.goals DESC,s.assists DESC,s.appearances ASC LIMIT 20").bind(id).all(),
      db.prepare("SELECT e.id,e.match_id AS matchId,e.team_id AS teamId,e.type,e.minute,CASE WHEN p.profile_visibility='public' AND p.media_consent=1 THEN COALESCE(p.public_name,p.first_name||' '||substr(p.last_name,1,1)||'.') ELSE 'Giocatore' END AS playerName,CASE WHEN ap.profile_visibility='public' AND ap.media_consent=1 THEN COALESCE(ap.public_name,ap.first_name||' '||substr(ap.last_name,1,1)||'.') ELSE NULL END AS assistPlayerName FROM match_events e JOIN matches m ON m.id=e.match_id LEFT JOIN players p ON p.id=e.player_id LEFT JOIN players ap ON ap.id=e.assist_player_id WHERE e.tournament_id=? AND m.status IN ('official','rectified') ORDER BY e.match_id,e.minute,e.created_at").bind(id).all(),
      db.prepare("SELECT so.id,so.competition_id AS competitionId,so.team_id AS teamId,so.outcome,so.position,so.decided_at AS decidedAt,t.name AS teamName,t.short_name AS shortName,t.primary_color AS primaryColor,t.crest_key AS crestKey,cs.name AS competitionName,cs.category,cs.division FROM season_outcomes so JOIN teams t ON t.id=so.team_id JOIN competition_settings cs ON cs.id=so.competition_id WHERE so.tournament_id=? AND so.outcome IN ('champion','finalist','promoted','safe','relegated','repechaged') ORDER BY cs.category,cs.division,CASE so.outcome WHEN 'champion' THEN 1 WHEN 'promoted' THEN 2 WHEN 'finalist' THEN 3 WHEN 'repechaged' THEN 4 WHEN 'safe' THEN 5 ELSE 6 END,so.position").bind(id).all(),
      db.prepare("SELECT mr.player_id AS playerId,mr.match_id AS matchId,mr.team_id AS teamId,mr.final_rating_tenths AS finalRatingTenths,mr.modifiers_json AS modifiersJson,m.match_day AS matchDay,m.starts_at AS startsAt,m.competition_id AS competitionId,m.category,COALESCE(p.public_name,p.first_name||' '||substr(p.last_name,1,1)||'.') AS playerName,p.photo_key AS photoKey,p.role,p.shirt_number AS shirtNumber,t.name AS teamName,t.short_name AS teamShort,t.primary_color AS teamColor,t.crest_key AS crestKey,COALESCE(s.appearances,0) AS appearances,COALESCE(s.goals,0) AS goals,COALESCE(s.assists,0) AS assists,COALESCE(s.clean_sheets,0) AS cleanSheets,COALESCE(s.mvp_awards,0) AS mvpAwards FROM match_player_ratings mr JOIN matches m ON m.id=mr.match_id JOIN players p ON p.id=mr.player_id JOIN teams t ON t.id=mr.team_id LEFT JOIN player_tournament_stats s ON s.player_id=p.id AND s.tournament_id=m.tournament_id WHERE mr.tournament_id=? AND m.status IN ('official','rectified') AND p.profile_visibility='public' AND p.media_consent=1 ORDER BY datetime(m.starts_at) DESC,mr.final_rating_tenths DESC LIMIT 400").bind(id).all(),
      db.prepare("SELECT a.id,a.match_id AS matchId,a.player_id AS playerId,a.type,a.title,a.note,a.awarded_at AS awardedAt FROM awards a JOIN players p ON p.id=a.player_id WHERE a.tournament_id=? AND a.status='published' AND a.type LIKE 'badge_%' AND p.profile_visibility='public' AND p.media_consent=1 ORDER BY a.awarded_at DESC").bind(id).all(),
    ]);
    return Response.json({ tournament, posts: posts.results, awards: awards.results, badges: badges.results, categories: categories.results, matches: matches.results.map((match:any)=>({...match,callups:{home:[],away:[]},events:events.results.filter((event:any)=>event.matchId===match.id)})), standings:standings.results, scorers:scorers.results, outcomes:outcomes.results, fantasyRatings:fantasyRatings.results.map((row:any)=>({...row,modifiers:JSON.parse(row.modifiersJson||"[]"),modifiersJson:undefined})) });
  } catch {
    return Response.json({ error: "Contenuti non disponibili" }, { status: 500 });
  }
}
